[FRAF-803] Update svgs
teamleadercrm/ui-icons pull request #425
Opened 2022-07-26 14:00 UTC by farazatarodi

[Jira](https://teamleader.atlassian.net/browse/FRAF-803)

Updated existing SVGs.
Added several new ones.
Renamed a few.

MC:
Icons should look ok. :)

2022-07-26 14:08 UTC, qubis741 approved these changes

2022-07-26 14:37 UTC, lorgan3 requested changes
Missing changelog entry(ies)

Renaming (=removing) icons seems like a breaking change btw

2022-07-26 14:48 UTC, lorgan3 approved these changes

2022-07-27 03:18 UTC, lowiebenoot approved these changes

2022-07-27 10:27 UTC, qubis741 commented
Manually checked :white_check_mark:

2022-07-27 11:09 UTC, merged